var myFullName;
console.log(myFullName);
myFullName="Anshu Dangi";
console.log(myFullName);
myFullName="Anshu Singh Dangi";
console.log(myFullName);
var myLove="I love only JS";
console.log(myLove);
var firstName="Anshu";
console.log("Firstname:",firstName);
var lastName="Dangi";
console.log("lastname:",lastName);
var age="23";
console.log("Age",age);
var address="laxmi chowk";
console.log("Address:",address);
var pinCode="470117";
console.log("Pincode",pinCode);
var gender="female";
console.log("gender",gender);
var isMarried="no";
console.log("Ismarried:",isMarried);